# Theme Settings
minimal_mistakes_skin: "default" # You can change this to: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
title: "Wishva Wijesooriya"
description: "Portfolio showcasing AI, ML, and Data Science projects"
url: "https://wishva12.github.io"

# Enable custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Custom CSS
head_scripts:
  - https://kit.fontawesome.com/your-font-awesome-kit.js # Optional: for icons

# Author Profile with Colors
author:
  name: "Wishva Wijesooriya"
  avatar: "/assets/images/profile-photo.jpg"
  bio: "Data Science undergraduate passionate about **AI, ML, and IoT** solutions 🚀"
  location: "📍 Minuwangoda, Sri Lanka"
  email: "wishva.wijesooriyaco@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Wishva12"
    - label: "LinkedIn" 
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/wishva-wijesooriya"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wishva.wijesooriyaco@gmail.com"


